spring:
  application:
    name: ZID Verifier
  
  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      jedis:
        pool:
          max-active: 10
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

# Provider Configuration
provider:
  base-url: http://localhost:43313

# Token Configuration
token:
  provider:
    # Client credentials (should be encrypted in production)
    client-id: ${TOKEN_CLIENT_ID}
    client-secret: ${TOKEN_CLIENT_SECRET}
    
    # Provider URLs
    create-token-url: ${provider.base-url}/v1/token/create
    refresh-token-url: ${provider.base-url}/v1/token/refresh
    
    # Token management settings
    access-token-buffer-minutes: 2  # Refresh 2 minutes before expiry
    refresh-token-buffer-days: 1    # Refresh 1 day before expiry
    
    # Redis settings
    redis:
      key-prefix: "zid:verifier:token:"
      access-token-key: "access_token"
      refresh-token-key: "refresh_token"
    
    # Retry settings
    retry:
      max-attempts: 3
      backoff-delay-ms: 1000
      max-backoff-delay-ms: 5000
    
    # Scheduling (in cron format)
    schedule:
      access-token: "0 */10 * * * *"    # Every 10 minutes
      refresh-token: "0 0 0 */5 * *"    # Every 5 days at midnight

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.zid.verifier.token: DEBUG
    org.springframework.data.redis: INFO